MinPlayersToStart: 2

titleToKiller:
  title: "Ты победил!"
  subtitle: "ты проходишь дальше"


nabludpunkt:
  world: "world"
  x: -27
  y: 67
  z: -1

colba1:
  world: "world"
  x: -1
  y: 76
  z: -17

colba2:
  world: "world"
  x: -1
  y: 76
  z: 18

